from app.tests.v1.admin.fetch_orders_endpoint import TestFetchOrdersEndpoint
from app.tests.v1.admin.update_order_endpoint import TestUpdateOrderEndpoint
from app.tests.v1.admin.post_new_food_item_endpoint import TestPostNewFoodItemEndpoint
from app.tests.v1.admin.fetch_order_endpoint import TestFetchOrderEndpoint