language: python

python:
  - "3.5"

script:
  - python setup.py build
  - python setup.py install
  - py.test --doctest-modules coveralls -v --cov coveralls --cov-report term-missing

after_success: 
  - coveralls